### ISSUE TITLE
discussion: default acl_agent_token for servers

### ISSUE THREAD

**Issue by discointheair** [ansible-collections/ansible-consul#119]
Hi

Consul servers are dropping “[WARN] agent: Node info update blocked by ACLs” messages without adding an "acl_agent_token". 

See:
[thread](https://gist.github.com/slackpad/d89ce0e1cc0802c3c4f2d84932fa3234)

ATM I workaround the problem with "acl_agent_token": <acl_master_token>
I would like to discuss how to solve this within the role. 

I see these ways: 

1.	 "acl_agent_token": <acl_master_token>
Very simple to implement in the role. But are there any security issues? 
```
{## Server ACLs ##}
{% if consul_acl_enable %}
 "acl_default_policy": "{{ consul_acl_default_policy }}",
 "acl_master_token": "{{ consul_acl_master_token }}",
 "acl_agent_token": "{{ consul_acl_master_token }}",
```

2.	Own token without restart
Give/Gen an acl_agent_token for the servers and add it also to the configs.
Start the servers 
Call the API with the master token and add the necessary acl rule.

3.	Own token with restart
Start the server 
Call the API with the master token, add the necessary acl rule and store it locally 
Add acl_agent_token configs
Restart servers

Maybe some one knows a better way?

**Comment by discointheair** [comment]
Hi
Has now one of you the same problem?
How do you implement this token automatically?

**Comment by groggemans** [comment]
The ACL code has been broken for a long time, and was only recently fixed again. I think this explains why not many people are experiencing this issue.

I've also just implemented ACL's in my test setup (that's why I fixed the ACL code). So I don't have that much experience with ACL's myself. I'm currently rather busy (moving to another place), but I'll try to check my logs and do some tests once I've got some more time again.

Please do report you findings/experience here!

**Comment by discointheair** [comment]
ATM I have no more acl problems (since Consul 0.9.3). But I do not really understand why a server needs this client token. For the next time I will use
` "acl_agent_token": "{{ consul_acl_master_token }}"`
.
But I can not say if this solution should be implemented in this role.
If there are new findings I will post it here.
