### ISSUE TITLE
'dict object' has no attribute 'consul_bind_address'

### ISSUE THREAD

**Issue by kikdevops** [ansible-collections/ansible-consul#128]
I run the role and receive an error:
`
TASK [brianshumate.consul : Create configuration] ***********************************************************************************************************************************************************************************************
task path: /home/user/ansible/roles/brianshumate.consul/tasks/config.yml:8
File lookup using /home/user/ansible/roles/brianshumate.consul/templates/config.json.j2 as file
fatal: [hostname.domain.tld]: FAILED! => {
    "failed": true, 
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'consul_bind_address'\n\nThe error appears to have been in '/home/user/ansible/roles/brianshumate.consul/tasks/config.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create configuration\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'consul_bind_address'"
}
    to retry, use: --limit @/home/user/ansible/site.retry
`

my inventory file
`
[consul_instances]
hostname.domain.tld consul_node_role=server consul_bootstrap_expect=true
`

my site.yml
`
- hosts: consul_instances
  roles:
    - { role: 'brianshumate.consul', tags: 'galaxy-consul' }
`

When I'm adding subtask and run it
`
- name: print to stdout
  debug:
    var: consul_bind_address
`

I see right address
`
ok: [hostname.domain.tld] => {
    "consul_bind_address": "x.x.x.x"
}
`

Anybody knows how to resolve this issue?

**Comment by calvinmorrow** [comment]
I'm having the same issue.  Haven't found a workaround yet.

**Comment by groggemans** [comment]
Thank you for using this role!

Can it be that you have another server with `consul_node_role: server` in your inventory that's not currently targeted?

You also need to make sure you have the `consul_bootstrap_expect` option set to true for all nodes in the cluster.

Are you setting up a single node cluster? If not, the problem might be in determining the `consul_bind_address` of another node then the currently targeted one. It might be interesting to have a debug print of the `consul_lan_servers`, `consul_wan_servers`, `consul_bootstrap_servers` and `hostvars` variables.

**Comment by brianshumate** [comment]
Hey there, @kikdevops; I think as @groggemans has suspected, your host inventory might be incompletely defined, so you definitely want to make sure it has the fields he mentioned.

**Comment by lilithfr** [comment]
I have the same issue, the variable consul_bind_address seems set properly.
I have 3 servers and 2 servers are configured through Ansible and this role. I use the following group configuration: 
consul_node_role: server
consul_bootstrap_expect: true
consul_join: [ 192.168.0.5 ]
consul_encrypt_enabled: true

I checked the consul_bind_address with a debug task


TASK [brianshumate.consul : print consul_bind_address] ****************************************************************************************************************************************************************************************************************
ok: [consul2] => {
    "consul_bind_address": "192.168.0.4"
}

TASK [brianshumate.consul : Create configuration] ************************************************************************************************************************************************************************************************************
fatal: [consul2]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'consul_bind_address'\n\nThe error appears to have been in '/home/vagrant/.ansible/roles/brianshumate.consul/tasks/config.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create configuration\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'consul_bind_address'"}

If I set "consul_bind_address" manually in my group configuration, the template works properly but I cannot use variable like 'ansible_bond0.ipv4.address' otherwise retry_join will be wrong in the config so I have to set the exact ip

**Comment by groggemans** [comment]
@lilithfr The role was not designed to deploy 2/3 of the servers. With a little tweaking this could work, but you'll have to add the information about the third server in your inventory, and then only target the 2 servers you're configuring.

If you don't do this, the bootstrap_expect value will be wrong, and you might run into problems while bootstrapping. (This is not a problem when you're only deploying clients. Then you can just provide the gossip key and `consul_join` addresses).

In the above run you're only targeting a single node, depending on your configuration this might be a problem. As Ansible won't be able to determine the consul_bind_address of the other server(s).

If you're able to use static IP's you can always set the `consul_bind_address` in your *inventory* or *host_vars*. This should solve any lookup problems. Another option (although buggy in most ansible versions) is the `consul_gather_server_facts` option.

**Comment by lilithfr** [comment]
I have a little more detail, the easy appear only with multiple servers in order to generate retry_join.
The call to hostvars[server]['consul_bind_address'] return undefined when server is not the current.

**Comment by groggemans** [comment]
@lilithfr This is exactly as I suspected, but this should only happen if you're not running the playbook against all servers and you didn't explicitly define `consul_bind_address` in your *inventory* or *host_vars* files.
(the `consul_gather_server_facts` option is another solution for some ansible versions)

**Comment by lilithfr** [comment]
@groggemans thank you this part works now.

**Comment by groggemans** [comment]
@kikdevops Have you been able to solve your problem with the above information?

**Comment by kikdevops** [comment]
Yes, everything works well with group of servers. Thanks a lot.
