### ISSUE TITLE
Return Code for is_unzip_installed fails

### ISSUE THREAD

**Issue by gentoo9ball** [ansible-collections/ansible-consul#388]
#311 #313 

I'm running this playbook to deploy extra clients. The unzip path shell command with delegate_to does not seem to be running. Any idea what would cause this? 

When deploying extra clients, I receive this error:
`FAILED! => {"msg": "The conditional check 'is_unzip_installed.rc == 1' failed. The error was: error while evaluating conditional (is_unzip_installed.rc == 1): 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/root/.ansible/roles/brianshumate.consul/tasks/asserts.yml': line 98, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install remotely if unzip is not installed on control host\n  ^ here\n"}`

**Comment by gentoo9ball** [comment]
Figured it out. I had a when condition on the role import. That condition was inherited by any tasks under the role. Therefore, it skipped any task trying to run on the original server. 

Thank you all

**Comment by brian-lamb-software-engineer** [comment]
im getting the exact same error, same line 98 on asserts.  thanks.  


but before that error comes up, it tries to unzip and fails, then falls back to installing remotely attempt where the error comes up. 

```
TASK [ansible-consul : Check if unzip is installed on control host] **************************************************************************************************************************************************
fatal: [10.124.10.9]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: invalid user: ‘ansible’\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
...ignoring

...

TASK [ansible-consul : Install remotely if unzip is not installed on control host]*****
fatal: [10.124.10.9]: FAILED! => {"msg": "The conditional check 'is_unzip_installed.rc == 1' failed. The error was: error while evaluating conditional (is_unzip_installed.rc == 1): 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/home/myuser/src/labos/ansible/roles/ansible-consul/tasks/asserts.yml': line 98, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install remotely if unzip is not installed on control host\n  ^ here\n"}
```

I have been adjusting the become_user, ansible_become, ansible_become_user, what a beast that can be... I think this is related to that. 
Plus its trying to `chown` but this is a windows server.  🤔 


Ok yeah, for me it was a become issue, i had to make sure become_user, become_password, ansible_becomeUser, ansible_become_password, ansible_become_method and ansible_runas_user was set in the vars file, or on the task for the host in a vars: block.  

Now i believe i resolved the first error above, so that the condition was never met for the 2nd error, which is related to the OP.  so this probably isnt a solution to the OP error.
