### ISSUE TITLE
get_url failing on releases.hashicorp.com

### ISSUE THREAD

**Issue by cory-p-oncota** [ansible-collections/ansible-consul#43]
OS: Ubuntu 14.04

Seems to be an issue with Python 2.7.6 and TLS 1.2-only servers?

```
TASK [brianshumate.consul : Get Consul package checksum file] ******************
fatal: [10.0.12.158]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for releases.hashicorp.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl"}
```

**Comment by misho-kr** [comment]
I thought it was issue with outdated OpenSSL which dos not support SNI.

One workaround is to manually download the Consul zip and checksum files and to place them in files/ folder.

**Comment by brianshumate** [comment]
I think the issue is indeed outdated OpenSSL / lack of SNI and this is one of several reasons why the role only supports recent versions of each supported OS as per the [project meta](https://github.com/brianshumate/ansible-consul/blob/master/meta/main.yml#L8-L21).

I can probably test for and support 15.04 but going back to 14.04 requires too many workarounds.

I'll try a run with Vivid and make a new release if it works well and see about supporting current - 1 versions of the different platforms.

**Comment by brianshumate** [comment]
I have verified that the role works with Ubuntu 15.04 (Vivid) and added it to the meta in the [0.11.2 release](https://github.com/brianshumate/ansible-consul/releases/tag/v1.11.2) as means to at least meet you in the middle.

Unfortunately and as I previously mentioned, the role doesn't and won't be able to support very old OS releases.

**Comment by cory-p-oncota** [comment]
No problem and the quick resolution is appreciated. Will light the needed fires to get our environment up to speed to support these constraints.
