### ISSUE TITLE
Config files and dir structure

### ISSUE THREAD

**Issue by groggemans** [ansible-collections/ansible-consul#53]
Currently the following config dir structure is used;
```
/etc/consul
└── .consul_bootstrapped
/etc/consul.d
├── bootstrap
│   └── config.json
├── client
│   └── config.json
└── server
    └── config.json
```
I would like to change this to a more common layout where the agent config resides in the `consul` dir. And all files in `consul.d` are included automatically.
```
/etc/consul
├── {{ consul_node_role }}.json
└── .consul_bootstrapped
/etc/consul.d
└── random_config.json
```
In this example I only added the config for the specific role of the agent. Is there a reason why the role currently provides all 3 configs? I would provide bootstrap/server to all servers and only client to clients.

Happy to provide a PR.

**Comment by brianshumate** [comment]
I think this is technically a good approach.

The roles are available on all systems because I created this and primarily use it for test labs and troubleshooting, so it is often very handy to be able to quickly and manually switch the role of a machine by just changing the appropriate bit in the systemd unit or init script rather than hunt for configuration details.

In order to more generalize the role, I would be supportive of this filesystem hierarchy and for dropping only the configuration needed based on node_role.

**Comment by groggemans** [comment]
I'll add an option to still produce all config for test setups.
