### ISSUE TITLE
Not compatible with Ansible 2.3.0.0 with python3 on Ubuntu 16.04

### ISSUE THREAD

**Issue by kevit** [ansible-collections/ansible-consul#57]
TASK [brianshumate.consul : Check Consul package checksum file] ****************
fatal: [4cas]: FAILED! => {"changed": false, "failed": true, "module_stderr": "/bin/sh: /usr/bin/python3: No such file or directory\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

ansible --version
ansible 2.3.0.0

vars:
  ansible_python_interpreter: "/usr/bin/python3"

**Comment by brianshumate** [comment]
Hey there Sergey,

Thanks for this report. The task you're showing (*Check Consul package checksum file*) runs locally by default, downloading the SHASUMS and zip files to the Ansible control host before copying the zip file to each remote system. It does this to conserve bandwidth and speed up deployment. 

However, if the host you're running Ansible from doesn't have Python 3 in `/usr/bin/python3`, then that would explain why you get this error.

You can set the `consul_install_remotely` variable to `true` and everything will be downloaded/installed only on the remote hosts, which would get you past this error (unless the remote hosts do not have Python 3 installed / available as `/usr/bin/python3`).

Also, I tried specifying `ansible_python_interpreter: "python3"` (without the path) and that worked for me as well since my Python 3 is not in `/usr/bin` on my Ansible host.

**Comment by brianshumate** [comment]
Hi,

Can you verify if passing the `python3` version without full path (i.e. `ansible_python_interpreter: "python3"`) works for you?

Thanks!

**Comment by brianshumate** [comment]
I'm going to close this as I think that there are no Python 3 incompatibilities in the role and one of the suggestions I gave should work. Please comment and I will reopen if not.
